### ISSUE TITLE
Study the different API possibilities related with map APIs.

### ISSUE THREAD

**Issue by UO283615** [Arquisoft/lomap_en2b#11]
We need to find a proper API to user.
We should focus on finding one that has unlimited accesses, and fits our necessities. In addition, it has to be efficient.

**Comment by jjgancfer** [comment]
As far as I know, we have these options:
- Google Maps (paid)
- Mapbox (free until 10,000 queries, then paid; uses OpenStreetMap data)
- Leaflet (technically not an API, but a wrapper around OpenStreetMap, I think)

Considering we want to avoid spending money, I think we should use Leaflet, even if none of us has used it.

**Comment by jjgancfer** [comment]
Since we are having the discussion of the architecture in another issue, I close it.
