### ISSUE TITLE
Properly detect that the user is not loged in

### ISSUE THREAD

**Issue by UO283615** [Arquisoft/lomap_en2b#119]
Redirect users to the login page when they are not loged in.

**Comment by jjgancfer** [comment]
When testing #130, the session seemed to follow when I logged in, so it may be fixed by now. Maybe was the same issue as in #123. Could you check if the code works with the refactor?

**Comment by andrrsin** [comment]
In #131 Request it has been added login as the default page, so you always must login before navigating elsewhere. And when you logut you are redirected to the log in page. There is however a small bug if you reload the page where you are just sent where you where but w/o session
