### ISSUE TITLE
Creation of a new logo for lomap

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/lomap_en2b#12]
I am planning on designing a new logo for lomap in order to make ou rproject stand out from the others. Plus we should try to decide some corporate colors to represent the project.

**Comment by jjgancfer** [comment]
Sounds great. Any idea about the colours we'll use?

**Comment by andrrsin** [comment]
I was believing on using pastel color tones as they easily mix both with light and dark mode. Also for the moment I'd go for a green+other color as maps, and apple maps have as principal colors greenish yellow and blue

**Comment by UO283615** [comment]
I think having a logo would be great. As for colors, I think green and blue would be good but we have to check the tones to keep the Map colorblind firendly.

**Comment by andrrsin** [comment]
![Lomap](https://user-images.githubusercontent.com/77900120/221431810-c1a40dbd-7bde-4c08-a2fb-e5830b7c480f.png)
I propose this logo for our webapp, I also have selected  the following colors:
Pastel red: #F24444
Pastel blue: #A0C4F2
Pastel green: #91BF4B
Pastel light green: #CDD9A3
Pastel light yellow: #F2E5D5
![image](https://user-images.githubusercontent.com/77900120/221431946-d5d7c49f-60d3-4323-8fa4-4199e1f63b0a.png)
These colors combine both with a light mode of the webapplication and a dark mode where the grey used is dark but not too much.

**Comment by plg22** [comment]
Nice logo created for our app
