### ISSUE TITLE
Architecture of the application

### ISSUE THREAD

**Issue by jjgancfer** [Arquisoft/lomap_en2b#14]
As you remember, part five of the documentation consists on "building blocks". Related to what I discussed with @andrrsin in [Issue 13](https://github.com/Arquisoft/lomap_en2b/issues/13#issuecomment-1435030316), I'd like some feedback on what I think we could use as architecture.

            
![diagram-7609396490844321024](https://user-images.githubusercontent.com/77108019/219787847-c67b3eb3-329e-4fa5-820d-c424dca268eb.png)

**Comment by UO283615** [comment]
I believe we will implement something like MVC architectural style with a N-tier architecture, so the service layer will communicate with the model and the view but these two won't communicate with each other directly. For the model part, or data storage, we have two different providers as you represented in the picture, the centralised DB and the SOLID pods.

**Comment by jjgancfer** [comment]
Since we are having the discussion in another issue (see [#13](https://github.com/Arquisoft/lomap_en2b/issues/13)), I'm closing this one.
