### ISSUE TITLE
Self-reports from the first deliverable

### ISSUE THREAD

**Issue by jjgancfer** [Arquisoft/lomap_en2b#28]
I have reviewed several of my teammates work, as well as written points 5, 7, 10 and 11 of the documentation.

Edit: I also participated in several issues: [Issue 13](https://github.com/Arquisoft/lomap_en2b/issues/13), [Issue 12](https://github.com/Arquisoft/lomap_en2b/issues/12) and [Issue 15](https://github.com/Arquisoft/lomap_en2b/issues/15), to name a few examples.

**Comment by UO283615** [comment]
In this deliverable we focused on writing the documentation. I wrote the parts 1, 6 and 8. Also, I took part on some discussions with my colleagues in the Issues and also included some terms on the glossary. 

[PR Of Doc6](https://github.com/Arquisoft/lomap_en2b/pull/16)  
[PR Of Doc8](https://github.com/Arquisoft/lomap_en2b/pull/17)  
[Issue where we were discussing things about the application](https://github.com/Arquisoft/lomap_en2b/issues/13)

**Comment by plg22** [comment]
We finished writing the first version of the documentation, I did 3 sections of it, section 2, 4 and 9, but obviously also helped my teammates if they commented some issue regarding their parts of the documentation. I also merged and commented on some pull requests. And all of us as a team, with issues or speking face to face, participated in every decision taken until this moment.

**Comment by andrrsin** [comment]
I made only one of the two expected documentation parts as I faced some familiar problems. That is the part 3.

I also helped in numerous issues trying to slowly sketch the structure of the project. The team has worked perfect even helping me with the missing part.
