### ISSUE TITLE
Correct Images in the docs.

### ISSUE THREAD

**Issue by plg22** [Arquisoft/lomap_en2b#31]
Section 3 images do not load properly.

**Comment by plg22** [comment]
Correct images in all sections

**Comment by jjgancfer** [comment]
Check no diagram is duplicated

**Comment by UO283615** [comment]
As with Issue #35 we should rebuild the documentation and close this issue if the pictures work fine.

**Comment by plg22** [comment]
Every image in the documentation version 0.1 works fine, and they appear just where they should
