### ISSUE TITLE
Help with deploying locally the documentation

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/lomap_en2b#37]
I believe the problem in the part 3 has been solved, however we cannot know unless we upload to master, there is a way to deploy the documentation at local level, next class I am going to ask how to do it precisely. This issue is closely related to #31 however this one hopefully will be closed on tuesday

**Comment by jjgancfer** [comment]
I built it last time locally and then pull-requested for the delivery. To do it, you have to install [*Ruby*](https://www.ruby-lang.org/en/downloads/) and its *asciidoctor* and *asciidoctor-diagrams* dependencies, which are installed by running the following command:
> gem install asciidoctor asciidoctor-diagram

Then you go to */docs* and run the following:

> npm install (only the first time)
> npm run build
