### ISSUE TITLE
Some libraries to use

### ISSUE THREAD

**Issue by plg22** [Arquisoft/lomap_en2b#41]
We are using some libraries.
### BACKEND
Express --> Easier routing in the backend.
Nodemon --> Compilation at runtime. Any update is automated.
Mongoose --> Interaction with our MongoDB database.

### FRONTEND
Axios --> Easy api request.
ReactDOM --> Facilitates interacting with the DOM.
MaterialUI --> Import some UI gadgets to use in the app.

**Comment by andrrsin** [comment]
Added for the frontend:
@tanstack/react-query
react-router-dom
