### ISSUE TITLE
About the map API

### ISSUE THREAD

**Issue by jjgancfer** [Arquisoft/lomap_en2b#42]
As some of you might have noticed, I have already working on the map implementation, starting last Friday and working on it since then. Thing is, the official Mapbox React example the [documentation](https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/) proportionates does not work (at least for me) and efforts to find other solutions online were moot since they were too complex for an amateur in React like me to understand. 

So, today I tried my hand doing it using the [other library/API](https://leafletjs.com/) we had considered, adding a [React-specific dependency](https://react-leaflet.js.org/) and updating the React-related packages due to compatibility issues. And it worked. So, would you like to continue using Mapbox, or go ahead with the other implementation?

**Comment by plg22** [comment]
I think as you have used leaflet and it worked, and you could not make it work with MapBox, we should commit to what it´s working.

**Comment by andrrsin** [comment]
I agree, today we should revise your version, as long as it works fine. It is perfect for me, as you said the Mapbox was an example It's not a constraint. I'm going to review the PR to have it added

**Comment by jjgancfer** [comment]
Closed as the issue has been solved.
