### ISSUE TITLE
Link Users to FrontEnd

### ISSUE THREAD

**Issue by andrrsin** [Arquisoft/lomap_en2b#47]
I am starting to develop parts of the front end. This frontend for the moment have no link to the users as my user is a boolean True. I will list here the components and pages that face this linking issue so when the Solid connection is implemented we can link everything faster.

INITIAL LIST:
Navbar - Component.
Home - Page.

**Comment by jjgancfer** [comment]
Revised version as of 21/03/2023:
* Navbar - Component
* Home - Page
* Map - Component
* AddLandmarks - Page
