### ISSUE TITLE
Write the documentation

### ISSUE THREAD

**Issue by UO283615** [Arquisoft/lomap_en2b#7]
We need to write the version 0.1 of the documentation.
The documentation can be found [here](https://github.com/Arquisoft/lomap_en2b/tree/master/docs).

- [x] Write the first 3 parts and glossary.
- [x] Write the rest of the documentation.

**Comment by andrrsin** [comment]
Im linking the issue #22 as this affects directly this issue

**Comment by plg22** [comment]
As of today, we have finished the first version of the documentation.
